version: "3.8"

services:
  ocpp-simulate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocpp-simulate
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
